### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './static/feature_database/concat_all_feature.npz'

### ISSUE THREAD

**Issue by MDwihardikKPutra** [danghieuan/Image-Retrieval-System#1]
(venv) C:\Users\Dyko Putra\image-retrieval-system>python server.py
2023-11-08 19:34:33.946235: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "C:\Users\Dyko Putra\image-retrieval-system\server.py", line 31, in <module>
    data = np.load(root_fearure_path)
  File "C:\Users\Dyko Putra\image-retrieval-system\venv\lib\site-packages\numpy\lib\npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './static/feature_database/concat_all_feature.npz'

**Comment by danghieuan** [comment]
Hello @MDwihardikKPutra,

It look like the _concat_all_feature.npz_ feature is missing, as mentioned in the report: 
`
FileNotFoundError: [Errno 2] No such file or directory: './static/feature_database/concat_all_feature.npz'
`

Please run the **Feature Extractor** process before run _server.py_
`
$ cd image-retrieval-system
`
`
$ python offline.py
`
